services:
  postgres:
    image: postgres:17-alpine
    container_name: patient-service-db
    restart: unless-stopped
    networks:
      - patient-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  patient-service:
#    image: patient-service:latest
#    build:
#      context: ./patient-service
#      dockerfile: Dockerfile
#    container_name: patient-service
#    restart: unless-stopped
#    networks:
#      - patient-network
#    ports:
#      - "${PATIENT_SERVICE_PORT}:4000"
#    environment:
#      SPRING_APPLICATION_NAME: ${PATIENT_SERVICE_APPLICATION_NAME}
#      SERVER_PORT: ${PATIENT_SERVICE_PORT}
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
#      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
#      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
#      BILLING_SERVICE_ADDRESS: ${BILLING_SERVICE_ADDRESS}
#      BILLING_SERVICE_PORT: ${BILLING_SERVICE_GRPC_PORT}
#    depends_on:
#      postgres:
#        condition: service_healthy
#      billing-service:
#        condition: service_started

  billing-service:
    image: billing-service:latest
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    restart: unless-stopped
    networks:
      - patient-network
    ports:
      - "${BILLING_SERVICE_PORT}:4001"
      - "${BILLING_SERVICE_GRPC_PORT}:9001"
    environment:
      SPRING_APPLICATION_NAME: ${BILLING_SERVICE_APPLICATION_NAME}
      SERVER_PORT: ${BILLING_SERVICE_PORT}
      GRPC_SERVER_PORT: ${BILLING_SERVICE_GRPC_PORT}

volumes:
  postgres_data:

networks:
  patient-network:
    driver: bridge
