services:
  postgres:
    image: postgres:17-alpine
    container_name: patient-service-db
    restart: unless-stopped
    networks:
      - patient-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  patient-service:
#    image: patient-service:latest
#    build:
#      context: ./patient-service
#      dockerfile: Dockerfile
#    container_name: patient-service
#    restart: unless-stopped
#    ports:
#      - "4000:4000"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_SQL_INIT_MODE: always
#    depends_on:
#      postgres:
#        condition: service_healthy

  billing-service:
    image: billing-service:latest
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    restart: unless-stopped
    networks:
      - patient-network
    ports:
      - "4001:4001"
      - "9001:9001"

volumes:
  postgres_data:

networks:
  patient-network:
    driver: bridge