### PUT update patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Another name",
  "email": "test@example.com",
  "address": "Some street",
  "dateOfBirth": "1984-10-12"
}

###